jsdecena/laracom

app/Shop/Categories/Repositories/CategoryRepository.php, composer.json, config/app.php, phpunit.xml, tests/CreatesApplication.php, tests/Unit/Address/AddressUnitTest.php, tests/Unit/Cart/CartUnitTest.php, tests/Unit/Categories/CategoryUnitTest.php, tests/Unit/PaymentMethod/PaymentMethodUnitTest.php, tests/Unit/Products/ProductUnitTest.php, tests/Unit/Provinces/ProvincesUnitTest.php
Hi just wanted you to look into this
I've update it to laravel 5.5 as well as the test
=> update to laravel 5.5

.env.example, .gitignore, README.md, app/Http/Kernel.php, app/Http/Middleware/TrustProxies.php, composer.json, composer.lock, config/app.php, config/broadcasting.php, config/filesystems.php, config/hashing.php, config/logging.php, config/queue.php, config/session.php, database/seeds/EmployeesTableSeeder.php, package-lock.json, package.json, resources/views/admin/addresses/list.blade.php, resources/views/front/carts/cart.blade.php, tests/CreatesApplication.php, tests/Feature/Admin/PaymentMethods/PaymentMethodFeatureTest.php, tests/Feature/Front/Cart/CartFeatureTest.php
=> Upgrade to laravel 5.6

app/Http/Controllers/Admin/EmployeeController.php, app/Shop/Employees/Repositories/EmployeeRepository.php, app/Shop/Employees/Repositories/Interfaces/EmployeeRepositoryInterface.php, tests/Feature/Admin/Employees/EmployeeFeatureTest.php
=> Iss 41 employee detail update error

app/Http/Controllers/Admin/Products/ProductController.php, resources/views/admin/products/create.blade.php, resources/views/admin/products/edit.blade.php, resources/views/admin/products/list.blade.php, resources/views/admin/products/show.blade.php, resources/views/admin/shared/categories.blade.php, resources/views/admin/shared/cities.blade.php, resources/views/admin/shared/products.blade.php, resources/views/admin/shared/provinces.blade.php
Resolve some layout issues on the admin side
=> Layout UI changes

app/Http/Controllers/Admin/Products/ProductController.php, database/seeds/DatabaseSeeder.php, database/seeds/WarehouseTableSeeder.php
The PR just basic features related to wareshouse do.
Default warehouse is added by a seed as well also checked when fetching a warehouse from database.
Nowhere in a admin panel the warehouse appears, everything is doing in background.
=> warehouse feature - storing a stock level for a default warehouse

app/Http/Controllers/Admin/Cities/CityController.php, app/Shop/PaymentMethods/Paypal/PaypalExpress.php, app/Shop/Shipping/Shippo/ShippoShipmentRepository.php
Remove dd() function on `update()` method in `CityController`.
Maybe someone forgets to remove it or leave here for some reason.
Improve docblock
Remove unused parameter
=> Remove dd() function in CityController, Improve docblock

resources/docs/1.0/index.md, resources/docs/1.0/installation.md, resources/docs/1.0/overview.md
add installation guide that clone from wiki
Still, need to improve, but will be acceptable for now
=> Add document installation guide

resources/docs/1.4.6/installation.md
When I first installed Laracom I had to look up the admin route in the code. The documentation was not clear on how the admin dashboard can be reached. In this PR I just added some information for the admin route.
Cheers
Sebastian
=> Documentation for the admin dashboard

app/Http/Controllers/Admin/Products/ProductController.php
=> fix: create product save repeat images bug.

resources/views/layouts/front/app.blade.php
=> horizontal scroll fix

resources/views/layouts/front/app.blade.php
#Google Analytics Fix ID
##already had the field in the .env file but in the url was not defined the variable
=> Google Analytics Fix ID

README.md, app/Helpers/helper.php, app/Http/Controllers/Admin/DashboardController.php, app/Providers/GlobalTemplateServiceProvider.php, composer.json, config/module.php, resources/docs/1.4.6/dev.md, resources/views/layouts/admin/app.blade.php, resources/views/layouts/admin/breadcumb.blade.php
=> breadcrumb enhancement

app/Http/Controllers/Front/AccountsController.php, resources/assets/js/custom.js, resources/views/front/accounts.blade.php
Able to see ordered purchased products in show order 
You can see your order in My Account " Orders" Tab.   Selecting a order, the purchased products are listed in the modal pop up.
=> Imp ord det

app/Http/Controllers/Front/CustomerAddressController.php
Fix for issue # 177 (Exception at address update)
Whenever you try to update an existing address, an application error raise.
The PR solve the issue numer 177 as described in it.  However a better solution would problaby be to modify routes/web.php because for the update action there is no need to send to the controller the customer Id (it's self determined).
Regards.
=> Fix customer address update

app/Http/Controllers/Front/CustomerAddressController.php
little improvement for issue number #179
The address is marked as disable only if the address has no order tied. In all other cases the address is soft deleted as the original code was doing.
=> little improvement for address delete

app/Http/Controllers/Admin/Orders/OrderController.php, app/Shop/Orders/Repositories/Interfaces/OrderRepositoryInterface.php, app/Shop/Orders/Repositories/OrderRepository.php
=> Using Eloquent relations for addresses and couriers

resources/views/front/checkout.blade.php
=> Fixed missing 'shipping' variable in front/checkout.blade

app/Http/Controllers/Front/ProductController.php
=> Removed 'combo' variable in Front/ProductController@show

resources/views/layouts/search.blade.php
=> Fix XSS on search form

app/Http/Controllers/Front/ProductController.php, resources/views/front/carts/cart.blade.php, resources/views/front/checkout.blade.php, resources/views/front/products/product-list-table.blade.php, resources/views/front/products/product-list.blade.php
=> Responsive cart and bugfix

resources/views/front/products/product-list-table.blade.php
This PR solves the `it_shows_the_checkout_page_when_user_is_logged_in` test.
Test runing in `master`
=> Fix test CartFeatureTest

project/app/Shop/Categories/Repositories/CategoryRepository.php
Fixes issues with missing defaults within Category Repository.
Resolves #247
=> Adds defaults for slug and cover in Category Repository

project/app/Http/Controllers/Admin/Orders/OrderController.php, project/app/Shop/Carts/Requests/AddToCartRequest.php, project/app/Shop/Orders/Requests/UpdateOrderRequest.php, project/app/Shop/Products/Requests/CreateProductRequest.php, project/app/Shop/Products/Requests/UpdateProductRequest.php, project/resources/views/admin/products/create.blade.php, project/resources/views/admin/products/edit.blade.php, project/tests/Feature/Admin/Products/ProductFeatureTest.php, project/tests/Feature/Front/Cart/CartFeatureTest.php
Fixes #242 
Need to specify validator at integer input tag, beacase the status becomes abnormal in case of negative value or string.
I added a feature test code and confirmed the operation.
=> Fix/ validator at integer input tag

project/resources/views/front/products/product-list.blade.php
fixes duplicate image paths in product search #238
=> search results have duplicated image paths

project/app/Helpers/helper.php, project/app/Http/Controllers/Admin/DashboardController.php, project/app/Providers/GlobalTemplateServiceProvider.php, project/resources/docs/1.4.6/dev.md, project/resources/views/layouts/admin/app.blade.php, project/resources/views/layouts/admin/breadcrumb.blade.php
Fixes typo with breadcrumb spelling in variables and files.
=> Fixes typo in breadcrumb name.

project/resources/views/layouts/front/header-cart.blade.php
https://huntr.dev/users/b1nslashsh has fixed the Cross-site Scripting (XSS) vulnerability 🔨. b1nslashsh has been awarded $25 for fixing the vulnerability through the huntr bug bounty program 💵. Think you could fix a vulnerability like this?
Get involved at https://huntr.dev/
Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/laracom/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/packagist/jsdecena/laracom/1/README.md
`laracom` is vulnerable for reflected `xss` or `cross-site-scripting`
fix for xss in laracom
in line : https://github.com/jsdecena/laracom/blob/master/project/resources/views/layouts/front/header-cart.blade.php#L22
The expression `{ !! $data !!} Parses input without escape` , but instead using  `{{ …
=> Security Fix for Cross-site Scripting (XSS) - huntr.dev

project/app/Http/Controllers/Admin/EmployeeController.php, project/app/Http/Controllers/Admin/LoginController.php, project/app/Http/Controllers/Auth/CartLoginController.php, project/app/Http/Controllers/Auth/LoginController.php, project/app/Shop/Employees/Requests/CreateEmployeeRequest.php, project/app/Shop/Employees/Requests/LoginRequest.php, project/app/Shop/Employees/Requests/UpdateEmployeeRequest.php
Fix namespacing for symlinked employees requests
=> Fixes #260

project/app/Http/Controllers/Admin/Categories/CategoryController.php, project/app/Http/Controllers/Admin/Categories/Requests/CreateCategoryRequest.php, project/app/Http/Controllers/Admin/Categories/Requests/UpdateCategoryRequest.php, project/app/Http/Controllers/Admin/Countries/CountryController.php, project/app/Http/Controllers/Admin/Countries/Requests/UpdateCountryRequest.php
Simply running a unit test I discovered the issues mentioned by @dev-ishantripathi in https://github.com/jsdecena/laracom/issues/260
Both category requests, and also the country request had wrong namespacing. This PR fixes that.
(Sorry for pushing in separate PR:s)
=> Fixes #260 2nd part

README.md, docker-compose-m1.yml, project/app/Shop/OrderStatuses/Requests/UpdateOrderStatusRequest.php
My Runtime is M2 Mac.
When I run this docker-compose.yml, It occured 'docker: no matching manifest for linux/arm64/v8 in the manifest list entries.'
So, I made docker-compose.yml for Mac which mounted Apple Sillicon.
Along with it, I add message to README.md
=> About Apple Sillicon

project/composer.json, project/composer.lock, project/database/seeders/AttributeTableSeeder.php, project/database/seeders/BrandsTableSeeder.php, project/database/seeders/CategoriesTableSeeder.php, project/database/seeders/CategoryProductsTableSeeder.php, project/database/seeders/CourierTableSeeder.php, project/database/seeders/CustomerAddressesTableSeeder.php, project/database/seeders/CustomersTableSeeder.php, project/database/seeders/DatabaseSeeder.php, project/database/seeders/EmployeesTableSeeder.php, project/database/seeders/MyCitiesTableSeeder.php, project/database/seeders/MyCountryTableSeeder.php, project/database/seeders/MyProvincesTableSeeder.php, project/database/seeders/OrderStatusTableSeeder.php, project/database/seeders/ProductsTableSeeder.php, project/database/seeders/StatesTableSeeder.php, project/database/seeders/USCitiesTableSeeder.php
Hi, @jsdecena
First of all thanks for the nice project. 
I found some issues when running in my local related to db:seed which I have fixed and I hope this will make it easier for others.
Here are the details of my change
1.  my PHP version is 8.1 and I was getting this error. 
to fix it I updated the composer.json 
from 
```
"phpunit/phpunit": "~7.0"
```
to
```
"phpunit/phpunit": "~7.0|~8.0"
```
2.  Laravel 8, the seeds directory was renamed to the seeders directory and need to add a namespace for each seeder class, therefore, sedding by the class was giving an error.
I have renamed the seeds directory to seeders, added the namespace to each class ``` namespace Database\Seeders; ```  and updated composer.json autoload-dev
```
"autoload-dev": {
"psr-4": {
"Tests\\": "tests/",
"App\\": …
```
=> [fix] db:seed failed issues
